# Prefix
set -g prefix C-b
bind C-b send-prefix  # for nested tmux sessions (eg. tmux in ssh)

# Reload config with prefix + r
bind r source-file ~/.config/tmux/tmux.conf \; display 'Reloaded'

# Mouse support
set -g mouse on

# Start windows/panes at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows when one is closed
set -g renumber-windows on

# Better colors
set -g default-terminal 'tmux-256color'
set -sa terminal-features ',xterm-ghostty:RGB'

# Enable extended keys (for better support of certain key combinations)
set -g extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Move status bar to the top
set -g status-position top

# ghostty-ai-themes transparency
set -g window-style 'bg=default'
set -g window-active-style 'bg=default'
set -g allow-passthrough all

# --- Stolen from aadarwal ---

# General
set -g history-limit 50000  # more scrollback
set -g escape-time 0
set -g focus-events on
set -g allow-rename off

# Pane Controls
bind h split-window -v -c '#{pane_current_path}'
bind v split-window -h -c '#{pane_current_path}'

# Window navigation
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-Left select-window -t -1
bind -n M-Right select-window -t +1
bind -n M-S-Left swap-window -t -1 \; select-window -t -1
bind -n M-S-Right swap-window -t +1 \; select-window -t +1
