# show hidden files by default
[mgr]
show_hidden = true

[preview]
max_width  = 2000
max_height = 2000
image_delay = 10

# git plugin
[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"

# rich-preview plugin
[plugin]
prepend_previewers = [
    { url = "*.csv", run = "rich-preview"}, # csv files
    { url = "*.md", run = "rich-preview" }, # markdown (.md) files
    { url = "*.rst", run = "rich-preview"}, # restructured text (.rst) files
    { url = "*.ipynb", run = "rich-preview"}, # jupyter notebooks (.ipynb)
    { url = "*.json", run = "rich-preview"}, # json (.json) files
]
