# show hidden files by default
[mgr]
show_hidden = true

[preview]
max_width  = 2000
max_height = 2000
image_delay = 10

# git plugin
[[plugin.prepend_fetchers]]
id  = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id  = "git"
url = "*/"
run = "git"
